AA-01, AA-04 and AA-05 finished
Marthox1999/UV-Energy pull request #50
Opened 2020-03-01 20:25 UTC by Shinku24

AA-01: Add admins
AA-04: Disable admins
AA-05 Delete admins

2020-03-02 19:30 UTC, marthox requested changes
Corregir:
En Deshabilitar y Eliminar, recargar la pagina automaticamente despues de ejecutar la acción
Eliminar el boton de Selected Admin del sidebar

2020-03-16 17:11 UTC, marthox approved these changes

2020-03-16 17:21 UTC, marthox approved these changes

2020-03-17 03:55 UTC, emyesme approved these changes
Issue:
- AA-03 cuando modifico la contraseña del admin no se realiza el cambio, no me puedo logear con la nueva contraseña
Nota: no todas las paginas de tus historias tienen los modals al final unas todavia tienen solo el alert y otras el modal, hay que buscar uniformidad en esta situación.

2020-03-17 05:02 UTC, merged